### PR TITLE
Explain this fork in README

### PR DESCRIPTION
**Pull request by kili-ilo**
This will redirect curious Roc newcomers back to the core repos.

### CODE REVIEW

**Comment by kili-ilo** [comment]
@folkertdev, could you please review this PR for accuracy?

**Comment by folkertdev** [comment]
we mostly have this fork to pin an inkwell version. I don't think we have features (right now) that are not in upstream inkwell, but we have had to add some stuff in the past

**Comment by kili-ilo** [comment]
Thanks, I'll update the explanation!

**Comment by kili-ilo** [comment]
@folkertdev Updated.

**Review by folkertdev — APPROVED** [review]

**Pull request merged**
